// generated by sapper build at 2021-02-06T07:11:51.105Z
process.env.NODE_ENV = process.env.NODE_ENV || 'production';
process.env.PORT = process.env.PORT || 80;

console.log('Starting server on port ' + process.env.PORT);
require('./server/server.js');